import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Raleway } from "next/font/google"; // Importing Raleway font
import "./globals.css";
import ContextProvider from "@/components/ContextProvider/ContextProvider";

// Importing the Geist, Geist_Mono, Roboto fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Importing the Roboto font
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

// Importing the Raleway font
const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${raleway.variable} antialiased`} // Added Raleway font
      >
        <ContextProvider>
          <main className="max-w-[1440px] min-h-screen m-auto bg-[#04125a]">
            {children}
          </main>
        </ContextProvider>
      </body>
    </html>
  );
}
